# Generated by Django 5.0.4 on 2024-04-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePermission',
        ),
    ]
